# Generated by Django 5.1.2 on 2024-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0003_noticia_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='duracao',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='icone',
            field=models.CharField(default='locationIcon', max_length=100),
        ),
    ]
