# Generated by Django 5.1.2 on 2024-11-20 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0005_alter_noticia_options_alter_noticia_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
