# Generated by Django 5.1.2 on 2024-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0006_noticia_data_adicionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
