# Generated by Django 5.1.2 on 2024-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0007_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='data_adicionado',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='duracao',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
