# Generated by Django 5.1.2 on 2024-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0008_alter_noticia_options_remove_noticia_data_adicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='duracao',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
