# Generated by Django 5.1.2 on 2024-11-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0009_noticia_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='duracao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='duracao_visibilidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
