# Generated by Django 5.1.2 on 2024-11-21 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0011_remove_noticia_duracao_visibilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_adicionado'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_adicionado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
