# Generated by Django 5.1.2 on 2024-11-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0012_alter_noticia_options_noticia_data_adicionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='duracao',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
