# Generated by Django 5.1.2 on 2024-11-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0017_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
    ]
