# Generated by Django 5.1.2 on 2024-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0018_alter_noticia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_adicionado'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='duracao',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
